from iso9001_rules_check_tools.models import Clause


CLAUSE_CATALOG: tuple[Clause, ...] = (
    Clause(
        clause_id="4.1",
        clause_title="Understanding the organization and its context",
        clause_title_zh="\u7d44\u7e54\u53ca\u5176\u80cc\u666f",
        keywords=("organization", "context", "internal issues", "external issues", "\u80cc\u666f", "\u5229\u5bb3\u95dc\u4fc2\u4eba"),
        description="Look for text about the organization, its context, and relevant internal or external issues.",
    ),
    Clause(
        clause_id="4.2",
        clause_title="Understanding the needs and expectations of interested parties",
        clause_title_zh="\u4e86\u89e3\u5229\u76ca\u95dc\u4fc2\u4eba\u7684\u9700\u6c42\u53ca\u671f\u671b",
        keywords=("interested parties", "stakeholder", "requirements", "needs and expectations", "\u5229\u76ca\u95dc\u4fc2\u4eba", "\u9700\u6c42", "\u671f\u671b"),
        description="Look for identified interested parties and their relevant requirements.",
    ),
    Clause(
        clause_id="4.3",
        clause_title="Determining the scope of the quality management system",
        clause_title_zh="\u6c7a\u5b9a\u54c1\u8cea\u7ba1\u7406\u7cfb\u7d71\u7684\u7bc4\u570d",
        keywords=("scope", "quality management system", "qms scope", "\u7bc4\u570d", "\u54c1\u8cea\u7ba1\u7406\u7cfb\u7d71"),
        description="Look for the documented scope of the QMS and any applicable boundaries.",
    ),
    Clause(
        clause_id="4.4",
        clause_title="Quality management system and its processes",
        clause_title_zh="\u54c1\u8cea\u7ba1\u7406\u7cfb\u7d71\u53ca\u5176\u904e\u7a0b",
        keywords=("quality management system", "qms", "\u904e\u7a0b", "\u7cfb\u7d71"),
        description="Look for the organization's process-based quality management system and process interactions.",
    ),
    Clause(
        clause_id="5.1",
        clause_title="Leadership and commitment",
        clause_title_zh="\u9818\u5c0e\u8207\u627f\u8afe",
        keywords=("leadership", "commitment", "top management", "\u9818\u5c0e", "\u627f\u8afe"),
        description="Look for top management commitment, customer focus, and leadership actions.",
    ),
    Clause(
        clause_id="5.2",
        clause_title="Quality policy",
        clause_title_zh="\u54c1\u8cea\u653f\u7b56",
        keywords=("quality policy", "policy", "communicate", "\u54c1\u8cea\u653f\u7b56", "\u5ba3\u5c0e"),
        description="Look for a quality policy that is established, communicated, and available as a statement of intent.",
    ),
    Clause(
        clause_id="5.3",
        clause_title="Organizational roles, responsibilities and authorities",
        clause_title_zh="\u7d44\u7e54\u89d2\u8272\u3001\u8cac\u4efb\u53ca\u6b0a\u9650",
        keywords=("responsibility", "authority", "roles", "responsibilities", "\u8cac\u4efb", "\u6b0a\u9650", "\u89d2\u8272"),
        description="Look for assigned responsibilities and authorities within the organization.",
    ),
    Clause(
        clause_id="6.1",
        clause_title="Actions to address risks and opportunities",
        clause_title_zh="\u5c0d\u98a8\u96aa\u53ca\u6a5f\u6703\u7684\u63aa\u65bd",
        keywords=("risk", "opportunity", "action", "risks and opportunities", "\u98a8\u96aa", "\u6a5f\u6703"),
        description="Look for risks, opportunities, and actions to address them.",
    ),
    Clause(
        clause_id="6.2",
        clause_title="Quality objectives and planning to achieve them",
        clause_title_zh="\u54c1\u8cea\u76ee\u6a19\u53ca\u5176\u898f\u5283",
        keywords=("quality objectives", "planning", "objective", "target", "\u54c1\u8cea\u76ee\u6a19", "\u898f\u5283"),
        description="Look for quality objectives, planning, and actions to achieve them.",
    ),
    Clause(
        clause_id="6.3",
        clause_title="Planning of changes",
        clause_title_zh="\u8b8a\u66f4\u898f\u5283",
        keywords=("change", "changes", "planning of changes", "\u8b8a\u66f4", "\u898f\u5283"),
        description="Look for planned changes to the quality management system.",
    ),
    Clause(
        clause_id="7.1",
        clause_title="Resources",
        clause_title_zh="\u8cc7\u6e90",
        keywords=("resources", "provide", "infrastructure", "environment", "\u8cc7\u6e90", "\u74b0\u5883"),
        description="Look for resources required for the quality management system.",
    ),
    Clause(
        clause_id="7.1.1",
        clause_title="General",
        clause_title_zh="\u4e00\u822c",
        keywords=("general resources", "resources", "\u4e00\u822c"),
        description="Look for general resource planning and provision.",
    ),
    Clause(
        clause_id="7.1.2",
        clause_title="People",
        clause_title_zh="\u4eba\u529b",
        keywords=("people", "personnel", "competence", "\u4eba\u54e1", "\u4eba\u529b"),
        description="Look for personnel needed to implement the QMS.",
    ),
    Clause(
        clause_id="7.1.3",
        clause_title="Infrastructure",
        clause_title_zh="\u57fa\u790e\u8a2d\u65bd",
        keywords=("infrastructure", "equipment", "facilities", "\u57fa\u790e\u8a2d\u65bd", "\u8a2d\u5099"),
        description="Look for buildings, equipment, and other infrastructure.",
    ),
    Clause(
        clause_id="7.1.4",
        clause_title="Environment for the operation of processes",
        clause_title_zh="\u904b\u4f5c\u904e\u7a0b\u7684\u74b0\u5883",
        keywords=("environment", "work environment", "process environment", "\u74b0\u5883", "\u5de5\u4f5c\u74b0\u5883"),
        description="Look for the environment needed to operate processes effectively.",
    ),
    Clause(
        clause_id="7.1.5",
        clause_title="Monitoring and measuring resources",
        clause_title_zh="\u76e3\u8996\u548c\u91cf\u6e2c\u8cc7\u6e90",
        keywords=("monitoring", "measurement", "calibration", "measuring equipment", "\u91cf\u6e2c", "\u6821\u6e96"),
        description="Look for monitoring and measurement resources, including calibration.",
    ),
    Clause(
        clause_id="7.1.6",
        clause_title="Organizational knowledge",
        clause_title_zh="\u7d44\u7e54\u77e5\u8b58",
        keywords=("knowledge", "organizational knowledge", "\u77e5\u8b58", "\u7d93\u9a57"),
        description="Look for knowledge needed to operate processes and achieve conformity.",
    ),
    Clause(
        clause_id="7.1.7",
        clause_title="Competence",
        clause_title_zh="\u80fd\u529b",
        keywords=("competence", "competent", "training", "\u80fd\u529b", "\u8a13\u7df4"),
        description="Look for competence, training, and actions to achieve competence.",
    ),
    Clause(
        clause_id="7.2",
        clause_title="Competence",
        clause_title_zh="\u80fd\u529b",
        keywords=("competence", "competent", "training", "\u80fd\u529b", "\u8a13\u7df4"),
        description="Look for competence, training, and actions to achieve competence.",
    ),
    Clause(
        clause_id="7.3",
        clause_title="Awareness",
        clause_title_zh="\u610f\u8b58",
        keywords=("awareness", "aware", "awareness of policy", "\u610f\u8b58"),
        description="Look for awareness of policy, objectives, and contribution to effectiveness.",
    ),
    Clause(
        clause_id="7.4",
        clause_title="Communication",
        clause_title_zh="\u6e9d\u901a",
        keywords=("communication", "communicate", "\u6e9d\u901a"),
        description="Look for internal and external communication requirements.",
    ),
    Clause(
        clause_id="7.5",
        clause_title="Documented information",
        clause_title_zh="\u6210\u6587\u8cc7\u8a0a",
        keywords=("documented information", "document", "records", "\u6587\u4ef6", "\u7d00\u9304"),
        description="Look for controlled documents, records, and other documented information.",
    ),
    Clause(
        clause_id="7.5.1",
        clause_title="General",
        clause_title_zh="\u4e00\u822c",
        keywords=("documented information", "\u6210\u6587\u8cc7\u8a0a"),
        description="Look for the general requirements for documented information.",
    ),
    Clause(
        clause_id="7.5.2",
        clause_title="Creating and updating",
        clause_title_zh="\u5efa\u7acb\u53ca\u66f4\u65b0",
        keywords=("create", "update", "document control", "\u66f4\u65b0", "\u5efa\u7acb"),
        description="Look for how documented information is created and updated.",
    ),
    Clause(
        clause_id="7.5.3",
        clause_title="Control of documented information",
        clause_title_zh="\u6210\u6587\u8cc7\u8a0a\u4e4b\u63a7\u5236",
        keywords=("document control", "documented information", "retention", "distribution", "access", "retrieve", "\u63a7\u5236"),
        description="Look for retention, distribution, access, and control of documented information.",
    ),
    Clause(
        clause_id="8.1",
        clause_title="Operational planning and control",
        clause_title_zh="\u71df\u904b\u898f\u5283\u53ca\u63a7\u5236",
        keywords=("operation", "operational planning", "control of production", "\u71df\u904b", "\u63a7\u5236"),
        description="Look for planning and controlling the operational processes.",
    ),
    Clause(
        clause_id="8.2",
        clause_title="Requirements for products and services",
        clause_title_zh="\u7522\u54c1\u53ca\u670d\u52d9\u7684\u8981\u6c42",
        keywords=("requirements", "customer requirements", "products and services", "\u8981\u6c42"),
        description="Look for communication, determination, and review of requirements.",
    ),
    Clause(
        clause_id="8.3",
        clause_title="Design and development of products and services",
        clause_title_zh="\u7522\u54c1\u53ca\u670d\u52d9\u7684\u8a2d\u8a08\u8207\u958b\u767c",
        keywords=("design", "development", "design review", "design and development", "\u8a2d\u8a08", "\u958b\u767c"),
        description="Look for design and development planning, inputs, controls, and outputs.",
    ),
    Clause(
        clause_id="8.4",
        clause_title="Control of externally provided processes, products and services",
        clause_title_zh="\u5916\u90e8\u63d0\u4f9b\u904e\u7a0b\u3001\u7522\u54c1\u53ca\u670d\u52d9\u4e4b\u63a7\u5236",
        keywords=("external providers", "suppliers", "outsource", "procured", "\u4f9b\u61c9\u5546", "\u5916\u90e8"),
        description="Look for purchasing and control of externally provided processes and services.",
    ),
    Clause(
        clause_id="8.5",
        clause_title="Production and service provision",
        clause_title_zh="\u7522\u54c1\u548c\u670d\u52d9\u63d0\u4f9b",
        keywords=("production", "service provision", "work instructions", "\u751f\u7522", "\u670d\u52d9"),
        description="Look for controlled production and service delivery activities.",
    ),
    Clause(
        clause_id="8.5.1",
        clause_title="Control of production and service provision",
        clause_title_zh="\u751f\u7522\u8207\u670d\u52d9\u63d0\u4f9b\u4e4b\u63a7\u5236",
        keywords=("production", "service provision", "control", "\u63a7\u5236"),
        description="Look for controls applied during production and service provision.",
    ),
    Clause(
        clause_id="8.5.2",
        clause_title="Identification and traceability",
        clause_title_zh="\u8b58\u5225\u8207\u53ef\u8ffd\u6eaf\u6027",
        keywords=("identification", "traceability", "trace", "\u8ffd\u6eaf", "\u8b58\u5225"),
        description="Look for identification status and traceability controls.",
    ),
    Clause(
        clause_id="8.5.3",
        clause_title="Property belonging to customers or external providers",
        clause_title_zh="\u5c6c\u65bc\u5ba2\u6236\u6216\u5916\u90e8\u63d0\u4f9b\u8005\u7684\u8ca1\u7522",
        keywords=("customer property", "external provider property", "\u5ba2\u6236\u8ca1\u7522"),
        description="Look for customer or external provider property under control.",
    ),
    Clause(
        clause_id="8.5.4",
        clause_title="Preservation",
        clause_title_zh="\u4fdd\u5b58",
        keywords=("preservation", "storage", "handling", "packaging", "\u4fdd\u5b58", "\u5132\u5b58"),
        description="Look for preservation of outputs, packaging, handling, and storage.",
    ),
    Clause(
        clause_id="8.5.5",
        clause_title="Post-delivery activities",
        clause_title_zh="\u4ea4\u4ed8\u5f8c\u6d3b\u52d5",
        keywords=("post-delivery", "after-sales", "warranty", "service follow-up", "\u4ea4\u4ed8\u5f8c"),
        description="Look for post-delivery support and activities.",
    ),
    Clause(
        clause_id="8.5.6",
        clause_title="Control of changes",
        clause_title_zh="\u8b8a\u66f4\u4e4b\u63a7\u5236",
        keywords=("change", "changes", "control of changes", "\u8b8a\u66f4"),
        description="Look for control of production or service changes.",
    ),
    Clause(
        clause_id="8.6",
        clause_title="Release of products and services",
        clause_title_zh="\u7522\u54c1\u548c\u670d\u52d9\u4e4b\u653e\u884c",
        keywords=("release", "inspection", "acceptance", "approval", "\u653e\u884c", "\u9a57\u6536"),
        description="Look for product or service release criteria and acceptance.",
    ),
    Clause(
        clause_id="8.7",
        clause_title="Control of nonconforming outputs",
        clause_title_zh="\u4e0d\u7b26\u5408\u8f38\u51fa\u4e4b\u63a7\u5236",
        keywords=("nonconforming", "nonconformity", "reject", "rework", "\u4e0d\u7b26\u5408", "\u6539\u6b63"),
        description="Look for handling of nonconforming outputs.",
    ),
    Clause(
        clause_id="9.1",
        clause_title="Monitoring, measurement, analysis and evaluation",
        clause_title_zh="\u76e3\u8996\u3001\u91cf\u6e2c\u3001\u5206\u6790\u8207\u8a55\u4f30",
        keywords=("monitoring", "measurement", "analysis", "evaluation", "\u76e3\u8996", "\u5206\u6790", "\u8a55\u4f30"),
        description="Look for monitoring, measurement, analysis, and evaluation activities.",
    ),
    Clause(
        clause_id="9.1.1",
        clause_title="General",
        clause_title_zh="\u4e00\u822c",
        keywords=("monitoring", "measurement", "analysis", "\u4e00\u822c"),
        description="Look for the general requirements for monitoring and evaluation.",
    ),
    Clause(
        clause_id="9.1.2",
        clause_title="Customer satisfaction",
        clause_title_zh="\u5ba2\u6236\u6eff\u610f\u5ea6",
        keywords=("customer satisfaction", "feedback", "survey", "\u5ba2\u6236\u6eff\u610f\u5ea6"),
        description="Look for measurement of customer satisfaction and related feedback.",
    ),
    Clause(
        clause_id="9.1.3",
        clause_title="Analysis and evaluation",
        clause_title_zh="\u5206\u6790\u8207\u8a55\u4f30",
        keywords=("analysis", "evaluation", "data analysis", "\u5206\u6790", "\u8a55\u4f30"),
        description="Look for analysis and evaluation of QMS performance data.",
    ),
    Clause(
        clause_id="9.2",
        clause_title="Internal audit",
        clause_title_zh="\u5167\u90e8\u7a3d\u6838",
        keywords=("internal audit", "audit", "auditor", "\u7a3d\u6838"),
        description="Look for internal audit planning, execution, and reporting.",
    ),
    Clause(
        clause_id="9.3",
        clause_title="Management review",
        clause_title_zh="\u7ba1\u7406\u5be9\u67e5",
        keywords=("management review", "review meeting", "\u5be9\u67e5", "\u7ba1\u7406\u5be9\u67e5"),
        description="Look for management review inputs, outputs, and decisions.",
    ),
    Clause(
        clause_id="10.1",
        clause_title="General",
        clause_title_zh="\u4e00\u822c",
        keywords=("improvement", "general improvement", "\u6539\u9032"),
        description="Look for general improvement requirements.",
    ),
    Clause(
        clause_id="10.2",
        clause_title="Nonconformity and corrective action",
        clause_title_zh="\u4e0d\u7b26\u5408\u53ca\u6539\u5584\u884c\u52d5",
        keywords=("corrective action", "nonconformity", "root cause", "corrective", "\u6539\u5584\u884c\u52d5", "\u6839\u672c\u539f\u56e0"),
        description="Look for corrective action to address nonconformities and their causes.",
    ),
    Clause(
        clause_id="10.3",
        clause_title="Continual improvement",
        clause_title_zh="\u6301\u7e8c\u6539\u9032",
        keywords=("continual improvement", "improvement", "enhance", "\u6301\u7e8c\u6539\u9032"),
        description="Look for continual improvement of the QMS.",
    ),
)


def default_clause_catalog() -> tuple[Clause, ...]:
    return CLAUSE_CATALOG
